import {
  DESIGN_HEIGHT,
  DESIGN_VERSION,
  DESIGN_WIDTH,
  type Design,
} from './design';

export function createSampleDesign(): Design {
  return {
    version: DESIGN_VERSION,
    width: DESIGN_WIDTH,
    height: DESIGN_HEIGHT,
    pages: [
      {
        id: 'page-1',
        background: '#fff2f7',
        elements: [
          {
            id: 'top-decoration',
            type: 'shape',
            x: 70,
            y: 56,
            width: 940,
            height: 250,
            rotation: 0,
            opacity: 1,
            shape: 'rectangle',
            fill: '#ffd7e5',
          },
          {
            id: 'photo',
            type: 'image',
            x: 190,
            y: 430,
            width: 700,
            height: 500,
            rotation: 0,
            opacity: 1,
            assetId: 'builtin:birthday-photo',
          },
          {
            id: 'title',
            type: 'text',
            x: 130,
            y: 130,
            width: 820,
            height: 130,
            rotation: 0,
            opacity: 1,
            text: '오늘은 제 생일이에요!',
            fontFamily: 'Pretendard',
            fontSize: 72,
            fontWeight: 700,
            color: '#b52262',
            textAlign: 'center',
          },
          {
            id: 'name',
            type: 'text',
            x: 190,
            y: 310,
            width: 700,
            height: 80,
            rotation: 0,
            opacity: 1,
            text: '김생일',
            fontFamily: 'Pretendard',
            fontSize: 44,
            fontWeight: 600,
            color: '#5a2740',
            textAlign: 'center',
          },
          {
            id: 'date',
            type: 'text',
            x: 190,
            y: 970,
            width: 700,
            height: 60,
            rotation: 0,
            opacity: 1,
            text: '2026년 8월 21일',
            fontFamily: 'Pretendard',
            fontSize: 32,
            fontWeight: 500,
            color: '#7b3d58',
            textAlign: 'center',
          },
          {
            id: 'message',
            type: 'text',
            x: 140,
            y: 1080,
            width: 800,
            height: 100,
            rotation: 0,
            opacity: 1,
            text: '저의 특별한 날을 함께 축하해 주세요',
            fontFamily: 'Pretendard',
            fontSize: 36,
            fontWeight: 500,
            color: '#5a2740',
            textAlign: 'center',
          },
          {
            id: 'bottom-decoration',
            type: 'shape',
            x: 870,
            y: 1170,
            width: 120,
            height: 120,
            rotation: 0,
            opacity: 1,
            shape: 'circle',
            fill: '#ffb6cf',
          },
        ],
      },
    ],
  };
}
